DELETE
FROM BATCH_STEP_EXECUTION_CONTEXT
WHERE STEP_EXECUTION_ID
          IN (
          SELECT STEP_EXECUTION_ID
          FROM BATCH_STEP_EXECUTION
          WHERE JOB_EXECUTION_ID IN
                (SELECT JOB_EXECUTION_ID FROM BATCH_JOB_EXECUTION where LAST_UPDATED < /*expiredDateTime*/0))