SELECT STRING_VAL
FROM BATCH_JOB_EXECUTION_PARAMS
WHERE JOB_EXECUTION_ID IN (SELECT JOB_EXECUTION_ID FROM BATCH_JOB_EXECUTION where LAST_UPDATED < /*expiredDateTime*/0)
  AND KEY_NAME = 'targetFilePath'