--マルチペイメント請求

ALTER TABLE MULPAYBILL
   ALTER COLUMN CONVENIENCE TYPE VARCHAR(6);

--マルチペイメント決済結果
ALTER TABLE MULPAYRESULT
   ALTER COLUMN CVSCODE TYPE VARCHAR(6);

--コンビニ名称
ALTER TABLE CONVENIENCE
   ALTER COLUMN CONVENICODE TYPE VARCHAR(6);

-- 定期受注決済 
ALTER TABLE PERIODICORDERSETTLEMENT 
   ALTER COLUMN CONVENICODE TYPE VARCHAR(6);