-- 2023-renew No14 from here
ALTER TABLE CARTGOODS ADD COLUMN RESERVEFLAG varchar(1) DEFAULT 0 NOT NULL ;
ALTER TABLE CARTGOODS ADD COLUMN RESERVEDELIVERYDATE TIMESTAMP(0);

COMMENT ON COLUMN CARTGOODS.RESERVEFLAG IS '取りおきフラグ';
COMMENT ON COLUMN CARTGOODS.RESERVEDELIVERYDATE IS '取りおきお届け希望日';
-- 2023-renew No14 to here
