CREATE TABLE RESTOCKANNOUNCEGOODS
(
    goodsSeq        NUMERIC(8) NOT NULL,
    reStockStatus   VARCHAR(1) NOT NULL,
    reStockTime    TIMESTAMP(0),
    registTime      TIMESTAMP(0) NOT NULL,
    updateTime      TIMESTAMP(0) NOT NULL
)
;

ALTER TABLE RESTOCKANNOUNCEGOODS
    ADD CONSTRAINT RESTOCKANNOUNCEGOODS_PKEY PRIMARY KEY (goodsSeq)
;

COMMENT ON TABLE RESTOCKANNOUNCEGOODS IS '入荷お知らせ商品';
COMMENT ON COLUMN RESTOCKANNOUNCEGOODS.goodsSeq IS '商品SEQ';
COMMENT ON COLUMN RESTOCKANNOUNCEGOODS.reStockStatus IS '入荷状態';
COMMENT ON COLUMN RESTOCKANNOUNCEGOODS.reStockTime IS '入荷日時';
COMMENT ON COLUMN RESTOCKANNOUNCEGOODS.registTime IS '登録日時';
COMMENT ON COLUMN RESTOCKANNOUNCEGOODS.updateTime IS '更新日時';

CREATE UNIQUE INDEX idx_reStockAnnounceGoods ON RESTOCKANNOUNCEGOODS (goodsSeq);