-- 2023-renew No14 from here
DROP TABLE IF EXISTS public.CALENDARNOTSELECTDATE;
CREATE TABLE CALENDARNOTSELECTDATE
(
    NotPossibleReserveDate          TIMESTAMP(0) NOT NULL
);

COMMENT ON TABLE CALENDARNOTSELECTDATE IS 'カレンダー選択不可日付';
COMMENT ON COLUMN CALENDARNOTSELECTDATE.NotPossibleReserveDate IS '予約不可日';
-- 2023-renew No14 to here
