CREATE TABLE RESTOCKANNOUNCEMAIL
(
    goodsSeq        NUMERIC(8) NOT NULL,
    memberInfoSeq   NUMERIC(8) NOT NULL,
    versionNo       NUMERIC(6) NOT NULL DEFAULT 1,
    deliveryId      VARCHAR(10),
    deliveryStatus  VARCHAR(2) NOT NULL,
    deliveryTime    TIMESTAMP(0),
    registTime      TIMESTAMP(0) NOT NULL,
    updateTime      TIMESTAMP(0) NOT NULL
)
;


COMMENT ON TABLE RESTOCKANNOUNCEMAIL IS '入荷お知らせメール';
COMMENT ON COLUMN RESTOCKANNOUNCEMAIL.goodsSeq IS '商品SEQ';
COMMENT ON COLUMN RESTOCKANNOUNCEMAIL.memberInfoSeq IS '会員SEQ';
COMMENT ON COLUMN RESTOCKANNOUNCEMAIL.versionNo IS '更新カウンタ';
COMMENT ON COLUMN RESTOCKANNOUNCEMAIL.deliveryId IS '配信ID';
COMMENT ON COLUMN RESTOCKANNOUNCEMAIL.deliveryStatus IS '配信状況';
COMMENT ON COLUMN RESTOCKANNOUNCEMAIL.deliveryTime IS '配信日時';
COMMENT ON COLUMN RESTOCKANNOUNCEMAIL.registTime IS '登録日時';
COMMENT ON COLUMN RESTOCKANNOUNCEMAIL.updateTime IS '更新日時';


-- ALTER TABLE RESTOCKANNOUNCEMAIL DROP CONSTRAINT RESTOCKANNOUNCEMAIL_PKEY;
-- ALTER TABLE RESTOCKANNOUNCEMAIL ADD CONSTRAINT RESTOCKANNOUNCEMAIL_PKEY PRIMARY KEY (goodsSeq,memberInfoSeq,versionNo);

-- DROP INDEX idx_restockannouncemail;
-- CREATE UNIQUE INDEX idx_reStockAnnounceMail ON RESTOCKANNOUNCEMAIL (goodsSeq,memberInfoSeq,versionNo);

-- DROP INDEX restockannouncemail_pkey;
CREATE INDEX restockannouncemail_pkey ON RESTOCKANNOUNCEMAIL (goodsSeq, memberInfoSeq, versionNo);
