COMMENT ON COLUMN GOODSGROUP.GOODSCLASSTYPE IS '薬品区分';

ALTER TABLE GOODSGROUP ADD COLUMN dentalMonopolySalesFlg VARCHAR(1) DEFAULT 0 NOT NULL;
COMMENT ON COLUMN GOODSGROUP.dentalMonopolySalesFlg IS '歯科専売フラグ';
