ALTER TABLE ORDERPERSON ALTER COLUMN orderAddress1 TYPE VARCHAR(40);

ALTER TABLE ORDERPERSON ALTER COLUMN orderAddress2 TYPE VARCHAR(40);

ALTER TABLE ORDERPERSON ALTER COLUMN orderAddress3 TYPE VARCHAR(71);