ALTER TABLE ORDERDELIVERY ALTER COLUMN receiverAddress1 TYPE VARCHAR(40);

ALTER TABLE ORDERDELIVERY ALTER COLUMN receiverAddress2 TYPE VARCHAR(40);

ALTER TABLE ORDERDELIVERY ALTER COLUMN receiverAddress3 TYPE VARCHAR(71);