DROP SEQUENCE IF EXISTS MAILBATCHSEQ;
DROP SEQUENCE IF EXISTS MAILREQUESTCODE;
DROP TABLE IF EXISTS MAILBATCHINPUT;

CREATE TABLE MAILBATCHINPUT
(
    MAILBATCHSEQ               NUMERIC(8,0) NOT NULL,
    MAILREQUESTCODE            NUMERIC(8,0) NOT NULL,
    MAILREQUESTNO              NUMERIC(8,0) NOT NULL,
    MAILBODY                   TEXT NOT NULL
)
;
ALTER TABLE MAILBATCHINPUT
    ADD CONSTRAINT MAILBATCHINPUT_PKEY PRIMARY KEY  (MAILBATCHSEQ, MAILREQUESTCODE)
;

COMMENT ON TABLE MAILBATCHINPUT IS 'メールバッチ入力';
COMMENT ON COLUMN MAILBATCHINPUT.MAILBATCHSEQ IS 'メールバッチSEQ';
COMMENT ON COLUMN MAILBATCHINPUT.MAILREQUESTCODE IS 'メールバッチコード';
COMMENT ON COLUMN MAILBATCHINPUT.MAILREQUESTNO IS 'メール要求番号';
COMMENT ON COLUMN MAILBATCHINPUT.MAILBODY IS 'メールボディ';

CREATE SEQUENCE MAILBATCHSEQ INCREMENT 1 MINVALUE 10000000 MAXVALUE 99999999 START 10000000;
CREATE SEQUENCE MAILREQUESTCODE INCREMENT 1 MINVALUE 10000000 MAXVALUE 99999999 START 10000000;

