DROP SEQUENCE IF EXISTS BATCHSEQ;
DROP SEQUENCE IF EXISTS REQUESTCODE;
DROP TABLE IF EXISTS BATCH_JOB_EXECUTION_PARAMS_EXTENSION;

CREATE TABLE BATCH_JOB_EXECUTION_PARAMS_EXTENSION
(
    BATCHSEQ               NUMERIC(8,0) NOT NULL,
    REQUESTCODE            NUMERIC(8,0) NOT NULL,
    REQUESTNO              NUMERIC(8,0) NOT NULL,
    REQUESTDATA            TEXT NOT NULL
)
;
ALTER TABLE BATCH_JOB_EXECUTION_PARAMS_EXTENSION
    ADD CONSTRAINT BATCH_JOB_EXECUTION_PARAMS_EXTENSION_PKEY PRIMARY KEY  (BATCHSEQ, REQUESTCODE)
;

COMMENT ON TABLE BATCH_JOB_EXECUTION_PARAMS_EXTENSION IS 'バッチJOBパラメータ';
COMMENT ON COLUMN BATCH_JOB_EXECUTION_PARAMS_EXTENSION.BATCHSEQ IS 'バッチSEQ';
COMMENT ON COLUMN BATCH_JOB_EXECUTION_PARAMS_EXTENSION.REQUESTCODE IS 'リクエストコード';
COMMENT ON COLUMN BATCH_JOB_EXECUTION_PARAMS_EXTENSION.REQUESTNO IS 'リクエストNo';
COMMENT ON COLUMN BATCH_JOB_EXECUTION_PARAMS_EXTENSION.REQUESTDATA IS 'リクエストデータ';

CREATE SEQUENCE BATCHSEQ INCREMENT 1 MINVALUE 10000000 MAXVALUE 99999999 START 10000000;
CREATE SEQUENCE REQUESTCODE INCREMENT 1 MINVALUE 10000000 MAXVALUE 99999999 START 10000000;

