-- 規格画像
CREATE TABLE GOODSIMAGE
(
    GOODSGROUPSEQ                  NUMERIC(8,0) NOT NULL,
    GOODSSEQ                       NUMERIC(8,0) NOT NULL,
    IMAGEFILENAME                  VARCHAR(100),
    DISPLAYFLAG                    VARCHAR(1),
    REGISTTIME                     TIMESTAMP(0) NOT NULL,
    UPDATETIME                     TIMESTAMP(0) NOT NULL
)
;
ALTER TABLE GOODSIMAGE
    ADD CONSTRAINT GOODSIMAGE_PKEY PRIMARY KEY  (GOODSGROUPSEQ, GOODSSEQ)
;
COMMENT ON TABLE GOODSIMAGE IS '規格画像'
;
COMMENT ON COLUMN GOODSIMAGE.GOODSGROUPSEQ IS '商品グループSEQ'
;
COMMENT ON COLUMN GOODSIMAGE.GOODSSEQ IS '商品SEQ'
;
COMMENT ON COLUMN GOODSIMAGE.IMAGEFILENAME IS '画像ファイル名'
;
COMMENT ON COLUMN GOODSIMAGE.DISPLAYFLAG IS '表示状態'
;
COMMENT ON COLUMN GOODSIMAGE.REGISTTIME IS '登録日時'
;
COMMENT ON COLUMN GOODSIMAGE.UPDATETIME IS '更新日時'
;
